# Generated by Django 2.2.5 on 2019-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farm_thumbnail',
            new_name='farm_image',
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_description',
            field=models.TextField(blank=True, verbose_name='農場説明'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=150, verbose_name='農場名'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='タイトル'),
        ),
    ]
