# Generated by Django 2.2.5 on 2019-10-03 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_auto_20191003_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_url',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
    ]
