# Generated by Django 2.2.5 on 2019-10-03 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_auto_20191003_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_postal_code1',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='半角数字で入力して下さい', regex='^[0-9]+$')], verbose_name='郵便番号1'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_postal_code2',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='半角数字で入力して下さい', regex='^[0-9]+$')], verbose_name='郵便番号2'),
        ),
    ]
