# Generated by Django 2.2.4 on 2019-10-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0009_auto_20191008_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
