# Generated by Django 2.2.4 on 2019-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0013_auto_20191016_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=20, verbose_name='農場名'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmrep_first_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='代表名'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmrep_last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='代表姓'),
        ),
    ]
