# Generated by Django 2.2.4 on 2019-10-18 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0014_auto_20191016_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='発送フラグ')),
                ('is_settled', models.BooleanField(default=False, verbose_name='決済フラグ')),
                ('stripe_id', models.CharField(max_length=200, verbose_name='stripe_id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文日付')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.AlterModelOptions(
            name='farmproduct',
            options={'verbose_name': '果物', 'verbose_name_plural': '果物'},
        ),
        migrations.AlterField(
            model_name='farmproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品サムネイル'),
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=2, verbose_name='注文数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.Order', verbose_name='注文')),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.FarmProduct', verbose_name='注文商品')),
            ],
        ),
    ]
