# Generated by Django 2.2.4 on 2019-10-18 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0015_auto_20191018_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='コメント作成日時'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='コメント更新日時'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='ショッピングカートユーザ'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='amount',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20)], max_length=2, verbose_name='ショッピングカート数量'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.FarmProduct', verbose_name='ショッピングカート商品'),
        ),
    ]
