# Generated by Django 2.2.5 on 2019-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0017_auto_20191018_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='コメント'),
        ),
    ]
