# Generated by Django 2.2.5 on 2019-10-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0018_auto_20191019_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='ordered_item',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='fruit.Order', verbose_name='注文'),
        ),
    ]
