# Generated by Django 2.2.5 on 2019-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0020_auto_20191022_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='product_description',
            field=models.TextField(blank=True, max_length=250, verbose_name='商品説明'),
        ),
    ]
